### PR TITLE
Remove test-runner

### LINKED ISSUE #144: If -Dtests=false, but -Dhse-python:tests=true, the test runner is not getting picked up
### Description

Test runner is not getting picked up correctly.

### Steps to reproduce

_No response_

### Linux Distribution

Any

### File System

Any

### Other System details

Any

### PR DESCRIPTION
**Pull request by tristan957**
test-runner was a poor solution in retrospect. Essentially our tests need scratch directories. These scratch directories need to be created and cleaned up. test-runner did that at the cost of the extra process overhead in addition to making everything harder to debug in gdb, for instance.

Fixes #144

Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

File: tests/functional/cli/kvs/create/name-invalid-chars.sh [hunk 1]
```diff
@@ -2,8 +2,10 @@
...
 # SPDX-License-Identifier: Apache-2.0
 #
-# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.
+# Copyright (C) 2021-2022 Micron Technology, Inc. All rights reserved.
 
 . common.subr
 
+trap remove_home EXIT
+
 cmd -e hse kvs create "$home" kvs!!
```
Comment (alexttx) [inline tests/functional/cli/kvs/create/name-invalid-chars.sh:11]: I'd put quotes around the kvs name on line 11 since it has magic shell characters.

Comment (tristan957) [reply tests/functional/cli/kvs/create/name-invalid-chars.sh:11]: I see. Yea I will change that and re-push

File: tests/functional/cli/version.sh [hunk 2]
```diff
@@ -2,10 +2,12 @@
 
 # SPDX-License-Identifier: Apache-2.0
 #
-# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.
+# Copyright (C) 2021-2022 Micron Technology, Inc. All rights reserved.
 
 . common.subr
 
+trap remove_home EXIT
```
Comment (alexttx) [inline tests/functional/cli/version.sh:9]: A function dedicated to trap cleanup (and documented as such) would be good for several reasons:
- in the future, we can add to cleanup function instead of re-editing every use of `trap`
- might avoid using `cmd` since it does things that trap might not want (replicate checks for FAKE or whatever else `cmd` does)

Comment (alexttx) [reply tests/functional/cli/version.sh:9]: Do any of these smokes use background tasks?  If so, more trap cleanup is needed.

Comment (tristan957) [reply tests/functional/cli/version.sh:9]: > Do any of these smokes use background tasks? If so, more trap cleanup is needed.

I am not aware of any.

> A function dedicated to trap cleanup (and documented as such) would be good

Makes sense. I will change the name of the current function to `cleanup` and remove the usage of `cmd` within it. In addition, I will add a comment to the function.

Comment (alexttx) [reply tests/functional/cli/version.sh:9]: There's black magic involved in successfully killing background jobs.  See:

https://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits

look for this:
```
trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT
```

**Review by alexttx — APPROVED** [review]

File: tests/functional/cli/version.sh (hunk 2 above)
Comment (tristan957) [reply tests/functional/cli/version.sh:9]: That's good to know. I might document this SO answer in common.subr in the event we ever need it.

Comment (tristan957) [reply tests/functional/cli/version.sh]: I could not get that to work properly.

File: tests/framework/lib/framework.c [hunk 3]
```diff
@@ -150,6 +157,36 @@ mtf_main(int argc, char **argv, struct mtf_test_coll_info *tci)
...
+    } else {
+        /* If home wasn't provided, use a temporary directory. */
+
+        argv_home = getenv("HSE_TEST_RUNNER_DIR");
+        if (argv_home)
+            goto touch;
+        argv_home = getenv("MESON_BUILD_ROOT");
+        if (argv_home)
+            goto touch;
+        argv_home = "/tmp";
```
Comment (beckerg) [inline tests/framework/lib/framework.c:169]: Is it possible somewhere to pass in the null string for argv_home, in which case (strlen() - 1) will go awry..

Comment (tristan957) [reply tests/framework/lib/framework.c:169]: argv_home is guaranteed to be non-null by the time it gets to the strlen func. See the if above this diff.

**Review by beckerg — APPROVED** [review]

File: tests/framework/lib/framework.c (hunk 3 above)
Comment (beckerg) [reply tests/framework/lib/framework.c:169]: not non-null, empty string, as in """"

Comment (tristan957) [reply tests/framework/lib/framework.c:169]: Oh whoops. Nice catch. Let me account for that.
